server:
  port: 8082
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            data-id: sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
      transport:
        dashboard: localhost:8080
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 2000
  sentinel:
    enabled: true



#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 2000