spring:
  redis:
    jedis:
      pool:
        max-active: 9
        min-idle: 1
        max-wait: 1000
    port: 6379
    host: localhost
    timeout: 1000
  application:
    name: cloud-server
  cloud:
    sentinel:
      log:
        dir:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false

server:
  port: 9003
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9003/eureka/

sentinel:
  resources:
    user:
      #      flow:
      #        count: 5
      degrade:
        count: 0.0001
    hello:
      flow:
        count: 1
pool:
  pp:
    max-active: 10