server:
  port: 8083
eureka:
  instance:
    hostname: eureka-server
    appname: eureka-center
  client:
    registerWithEureka: false # 单点的时候设置为 false 禁止注册自身
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000